## This notebook loads EPH data, cleans it and arranges it to be used as 'training sets'. 
That is, for fitting any Machine Learning model.

In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

import numpy as np
pd.options.display.max_columns = 99

from IPython.display import display, HTML

import glob

In [2]:
startyr = 2003
endyr = 2021

In [3]:
radio_ref = pd.read_csv('./../data/info/radio_ref.csv')
# radio_ref[['PROV','NOMPROV','DPTO', 'NOMDPTO']].drop_duplicates().to_csv('./../data/DPTO_PROV.csv', index = False)
dpto_region = pd.read_csv('./../data/info/DPTO_PROV_Region.csv')
radio_ref = radio_ref.merge(dpto_region)
AGLO_Region = radio_ref[['AGLOMERADO', 'Region']].drop_duplicates()

# Decision sobre cual es la region de un aglomerado. GBA tiene que ir a Gran Buenos Aires, aunque algunos de sus radios en partidos como Rodriguez, Escobar, etc sean region pampeana.
# Viedma Patagones, se tendria que tirar de un lado, y la mayoria de sus radios, son Patagonia.
# Se tiene que corregir a mano, porque el AGLO 0 SI tiene varias regiones.

AGLO_Region = AGLO_Region.loc[~((AGLO_Region.AGLOMERADO == 33) & (AGLO_Region.Region == 'Pampeana'))]
AGLO_Region = AGLO_Region.loc[~((AGLO_Region.AGLOMERADO == 93) & (AGLO_Region.Region == 'Pampeana'))]

### Match column names

names_censo = ['IX_TOT', 'P02', 'P03', 'CONDACT', 'AGLOMERADO',
    'V01', 'H05', 'H06', 'H07', 'H08', 'H09', 'H10', 'H11', 'H12', 'H16', 'H15', 'PROP', 'H14', 'H13',
      'P07', 'P08', 'P09', 'P10', 'P05']


names_EPH = ['IX_TOT','CH04','CH06','CONDACT', 'AGLOMERADO',
    'IV1', 'IV3', 'IV4','IV5','IV6','IV7','IV8','IV10','IV11','II1','II2','II7','II8','II9',
    'CH09','CH10','CH12','CH13','CH15']

col_mon = [u'P21', u'P47T', u'PP08D1', u'TOT_P12', u'T_VI', u'V12_M', u'V2_M', u'V3_M', u'V5_M']

In [4]:
cpi = pd.read_csv('./../data/info/indice_precios_Q.csv', index_col=0)

cpi.index = pd.to_datetime(cpi.index)
cpi = cpi['2003':]
cpi

                  index
Q
2003-02-15    63.473237
2003-05-15    63.693094
2003-08-15    63.876225
2003-11-15    64.426224
2004-02-15    65.013542
...                 ...
2020-11-15  3117.767507
2021-02-15  3484.919808
2021-05-15  3871.116549
2021-08-15  4299.972546
2021-11-15  4610.072612

[76 rows x 1 columns]

In [5]:
cpi_M = pd.read_csv('./../data/info/indice_precios_M.csv', index_col=0)
cpi_mes_actual = cpi_M.iloc[-1][0]

cpi_M.tail(10)

                  index
2021-01-15  3363.379502
2021-02-15  3483.607931
2021-03-15  3607.771991
2021-04-15  3736.361552
2021-05-15  3869.534351
2021-06-15  4007.453745
2021-07-15  4150.288913
2021-08-15  4298.215066
2021-09-15  4451.413658
2021-10-15  4610.072612

## Referencia de nivel de precios
## 2016 - 01 - 01

In [6]:
cpi_d = pd.read_csv('./../data/info/indice_precios_d.csv', index_col=0)
cpi_d.index = pd.to_datetime(cpi_d.index)

cpi_d.loc['2016-01-01']

index    661.924392
Name: 2016-01-01 00:00:00, dtype: float64

In [7]:
ix = cpi_d.loc['2016-01-01'].values[0]

In [8]:
### Correr la notebook "00 - deflator" para tener esto actualizado.
cpi_mes_actual

4610.072611944027

In [9]:
from pandas.tseries.offsets import MonthEnd

## Cargar EPHs

Los microdatos de la Encuesta Permanente de Hogares se pueden descargar con:

``git clone https://github.com/matuteiglesias/microdatos-EPH-INDEC.git``

(darle star al repositorio)

tomando pull del mismo repositorio se va a poder actualizar con los nuevos microdatos a medida que se publican. Siempre y cuando el repositorio se mantenga actualizado. Y hasta que no se supere la capacidad de almacenamiento en repo github.

In [10]:
import os

path ='./../../microdatos-EPH-INDEC/microdatos/' # depende de donde hayamos descargado los microdatos
# path ='./../../EPH/microdatos/' # depende de donde hayamos descargado los microdatos

for y in range(startyr, endyr):
    print(y)
    yr = str(y)[2:]
    allFiles = glob.glob(path + 'hogar/*'+str(yr)+'.txt')
    frame = pd.DataFrame()
    list_ = []
    for file_ in allFiles:
        df = pd.read_csv(file_,index_col=None, header=0, delimiter = ';',
                        usecols = ['CODUSU','ANO4','TRIMESTRE','IX_TOT', 'AGLOMERADO',
        'IV1', 'IV3', 'IV4','IV5','IV6','IV7','IV8','IV10','IV11','II1','II2','II7','II8','II9']) 
        ['II2', 'IV5', 'IX_TOT', 'II7', 'IV4', 'II1', 'IV7', 'IV6', 'IV11', 'IV8', 'IV3', 'II8', 'IV1', 'IV10', 'II9']
        
        print(len(df))
        list_ += [df]
    df = pd.concat(list_)

    # Correcciones Respuestas. Para que matchee censo
    df = df.loc[df.IV1 != 9]
    df['IV10'] = df['IV10'].map({1: 1, 2: 2, 3: 2, 0: 0, 9: 9})
    df['II9'] = df['II9'].map({1: 1, 2: 2, 3: 2, 4: 4, 0: 0})
    df['II7'] = df['II7'].map({1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 6, 8: 6, 9: 6, 0: 0})
    df['II9'] = df['II9'].map({1: 1, 2: 2, 3: 2, 4: 4, 0: 0})
    df['IX_TOT'] = df['IX_TOT'].clip(0, 8)
    
    hogar = df
    hogar = hogar.drop_duplicates()
    print(hogar.shape)

    allFiles = glob.glob(path + 'individual/usu_individual*'+str(yr)+'.txt')
    frame = pd.DataFrame()
    list_ = []
    for file_ in allFiles:
        print(file_)
    #     print(file_)
        df = pd.read_csv(file_,index_col=None, header=0, delimiter = ';',
                         usecols = ['CODUSU','ANO4','TRIMESTRE','CH04','CH06', 'AGLOMERADO', 'CH09','CH10','CH12','CH13','CH15'] +\
                         ['CH07', 'ESTADO','CAT_INAC','CAT_OCUP','PP07G1', 'PP07G2', 'PP07G3', 'PP07G4', 'PP07G_59', 'PP07H', 'PP07I', 'PP07J', 'PP07K',
                         'P47T', 'V3_M', 'T_VI', 'V12_M', 'TOT_P12', 'V5_M','V2_M', 'PP08D1', 'P21'])
        df = df.rename(columns = {'ESTADO': 'CONDACT'})

#         display(df.head())
# revisar estado, condact, cat ocup, cat inac.
    # For the regression training set. But for these the ANO4 TRIMESTRE is important.. Also we need more memory.
    #                      ['P21','P47T',,'CH08','CH16','TOT_P12','T_VI','V10_M','V11_M','V12_M','V18_M','V19_AM','V21_M','V2_M','V3_M',
    #             'V4_M','V5_M','V8_M','V9_M','PP08D1','PP08D4','PP08F1','PP08F2','PP08J1','PP08J2','PP08J3','PP10A','PP10C','PP10D','PP10E'])
#         print(len(df))
        list_ += [df]
    df = pd.concat(list_)

    # Correcciones Respuestas. Para que matchee censo
    df['CH15'] = df['CH15'].map({1:1, 2:1, 3:1, 4:2, 5:2, 9:0})
    df['CH06'] = df['CH06'].clip(0)
    df['CH09'] = df['CH09'].map({1:1, 2:2, 0:2, 3:2})
    df.loc[df['CH06'] < 14, 'CONDACT'] = 0 # Menores de 14 van con CONDACT 0, como en el Censo
    
    ## En Censo, Jardin y educacion especial no preguntan terminado si/no.
    df['CH12'] = df.CH12.replace(99, 0)
    df.loc[df.CH12.isin([0, 1, 9]), 'CH13'] = 0

#     df['MAYOR'] = df['CH06'] >= 14 
#     df['MAYOR'] = df['CH06'] // 7
#     df['CONDACT'] = df['CAT_OCUP'].fillna(-1)

    indiv = df
    indiv = indiv.dropna(subset = ['P47T'])
    print(indiv.shape)

    indiv_table = indiv[list(indiv.columns.difference(hogar.columns)) + ['CODUSU', 'ANO4', 'TRIMESTRE', 'AGLOMERADO']]
    EPH = hogar.merge(indiv_table, on = ['CODUSU', 'ANO4', 'TRIMESTRE', 'AGLOMERADO'], indicator = True)

    print('Hogar - Indiv merged:')
    print(EPH.shape)

    
#     EPH = EPH.loc[EPH.P47T != -9]
    
    EPH = EPH.merge(AGLO_Region)

    EPH_no_aglo = EPH.copy(); 
    EPH_no_aglo['AGLOMERADO'] = 0

    EPH = pd.concat([EPH, EPH_no_aglo]).reset_index(drop = True)

    print('No aglo agregado:')
    print(EPH.shape)
    
#     # Quarters / deflation
#     EPH['Q'] = EPH.ANO4.astype(str) + ':' + (3*EPH.TRIMESTRE).astype(str)
#     EPH['Q'] = pd.to_datetime(EPH['Q'], format='%Y:%m') + MonthEnd(1)
# #     cpi_ultimo_Q = indice_precios['index'].values[-1]
    
    # Quarters / deflation
    EPH['Q'] = EPH.ANO4.astype(str) + ':' + (3*EPH.TRIMESTRE).astype(str)
    EPH['Q'] = pd.to_datetime(EPH['Q'], format='%Y:%m') - pd.DateOffset(months=1) + pd.DateOffset(days=14)
    print(EPH['Q'].unique())


#     EPH[col_mon] = cpi_mes_actual*EPH[col_mon].div(EPH[['Q'] + col_mon].merge(cpi, on = 'Q', how = 'left')['index'].values, 0)
    EPH[col_mon] = ix*EPH[col_mon].div(EPH[['Q'] + col_mon].merge(cpi, on = 'Q', how = 'left')['index'].values, 0)
    
    # 2018Q3 -> Mar19 1.3156
    # 2018Q3 -> Abr19 1.361
#     EPH[col_mon] = 1.361*EPH[col_mon]
    
    EPH[col_mon] = EPH[col_mon].round()
    
    print('deflactado:')
    print(EPH.shape)
    display(EPH[col_mon].mean())
    
    training = EPH.rename(columns = dict(zip(names_EPH, names_censo)))
    
    if not os.path.exists('./../data/training/'):
        os.makedirs('./../data/training/')
    
    training.to_csv('./../data/training/EPHARG_train_'+str(yr)+'.csv', index = False)

2003
13180
13325
(26483, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t303.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t403.txt
(93244, 33)
Hogar - Indiv merged:
(96827, 49)
No aglo agregado:
(193654, 50)
['2003-08-15T00:00:00.000000000' '2003-11-15T00:00:00.000000000']
deflactado:
(193654, 51)

P21        1943.116073
P47T       2885.426389
PP08D1     1364.541750
TOT_P12     139.702831
T_VI        679.719376
V12_M        66.118417
V2_M        440.952276
V3_M         17.211883
V5_M         36.724757
dtype: float64

2004
12816
13809
13806
13497
(53873, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t104.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t204.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t304.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t404.txt
(187930, 33)
Hogar - Indiv merged:
(193742, 49)
No aglo agregado:
(387484, 50)
['2004-02-15T00:00:00.000000000' '2004-05-15T00:00:00.000000000'
 '2004-08-15T00:00:00.000000000' '2004-11-15T00:00:00.000000000']
deflactado:
(387484, 51)

P21        2108.899485
P47T       3006.964107
PP08D1     1507.223571
TOT_P12     153.789710
T_VI        636.016708
V12_M        87.074826
V2_M        410.739267
V3_M         12.432033
V5_M         25.509311
dtype: float64

2005
13597
13511
13807
13704
(54562, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t105.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t205.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t305.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t405.txt
(188755, 33)
Hogar - Indiv merged:
(194504, 49)
No aglo agregado:
(389008, 50)
['2005-02-15T00:00:00.000000000' '2005-05-15T00:00:00.000000000'
 '2005-08-15T00:00:00.000000000' '2005-11-15T00:00:00.000000000']
deflactado:
(389008, 51)

P21        2398.216623
P47T       3402.725291
PP08D1     1726.941652
TOT_P12     173.120177
T_VI        707.118306
V12_M        95.582862
V2_M        457.300405
V3_M         11.253794
V5_M         26.757141
dtype: float64

2006
13315
13962
18866
18655
(64739, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t106.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t206.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t306.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t406.txt
(222968, 33)
Hogar - Indiv merged:
(229210, 49)
No aglo agregado:
(458420, 50)
['2006-02-15T00:00:00.000000000' '2006-05-15T00:00:00.000000000'
 '2006-08-15T00:00:00.000000000' '2006-11-15T00:00:00.000000000']
deflactado:
(458420, 51)

P21        2865.542607
P47T       4004.896854
PP08D1     2097.342136
TOT_P12     199.843615
T_VI        783.070267
V12_M       105.671088
V2_M        502.828494
V3_M         12.259766
V5_M         30.858924
dtype: float64

2007
18360
18526
17891
(54739, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t107.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t207.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t407.txt
(188433, 33)
Hogar - Indiv merged:
(192995, 49)
No aglo agregado:
(385990, 50)
['2007-02-15T00:00:00.000000000' '2007-05-15T00:00:00.000000000'
 '2007-11-15T00:00:00.000000000']
deflactado:
(385990, 51)

P21        3101.049608
P47T       4283.201378
PP08D1     2317.029990
TOT_P12     200.669194
T_VI        862.889064
V12_M        99.186823
V2_M        580.854996
V3_M         14.253597
V5_M         33.218047
dtype: float64

2008
18123
18224
18326
18217
(72829, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t108.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t208.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t308.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t408.txt
(247819, 33)
Hogar - Indiv merged:
(253536, 49)
No aglo agregado:
(507072, 50)
['2008-02-15T00:00:00.000000000' '2008-05-15T00:00:00.000000000'
 '2008-08-15T00:00:00.000000000' '2008-11-15T00:00:00.000000000']
deflactado:
(507072, 51)

P21        3205.322814
P47T       4493.678164
PP08D1     2431.487887
TOT_P12     201.546660
T_VI        921.050940
V12_M       100.143112
V2_M        617.686557
V3_M         23.283372
V5_M         29.755384
dtype: float64

2009
17820
17904
18149
17807
(71622, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t109.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t209.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t309.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t409.txt
(240967, 33)
Hogar - Indiv merged:
(246169, 49)
No aglo agregado:
(492338, 50)
['2009-02-15T00:00:00.000000000' '2009-05-15T00:00:00.000000000'
 '2009-08-15T00:00:00.000000000' '2009-11-15T00:00:00.000000000']
deflactado:
(492338, 51)

P21        3286.780679
P47T       4602.621805
PP08D1     2532.504820
TOT_P12     201.042085
T_VI        945.279877
V12_M       101.216607
V2_M        653.824933
V3_M         24.360159
V5_M         30.452571
dtype: float64

2010
17813
17478
18045
17812
(71105, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t110.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t210.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t310.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t410.txt
(237055, 33)
Hogar - Indiv merged:
(241663, 49)
No aglo agregado:
(483326, 50)
['2010-05-15T00:00:00.000000000' '2010-02-15T00:00:00.000000000'
 '2010-08-15T00:00:00.000000000' '2010-11-15T00:00:00.000000000']
deflactado:
(483326, 51)

P21        3264.026314
P47T       4603.962452
PP08D1     2535.199344
TOT_P12     195.837290
T_VI        978.524892
V12_M        97.029177
V2_M        676.883251
V3_M         20.004030
V5_M         50.988194
dtype: float64

2011
17607
18001
17761
17686
(71010, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t111.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t211.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t311.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t411.txt
(231657, 33)
Hogar - Indiv merged:
(236506, 49)
No aglo agregado:
(473012, 50)
['2011-02-15T00:00:00.000000000' '2011-05-15T00:00:00.000000000'
 '2011-08-15T00:00:00.000000000' '2011-11-15T00:00:00.000000000']
deflactado:
(473012, 51)

P21        3415.177814
P47T       4839.015408
PP08D1     2687.495260
TOT_P12     184.858316
T_VI       1058.915423
V12_M       104.018947
V2_M        745.662296
V3_M         20.973946
V5_M         52.860181
dtype: float64

2012
17302
17636
17403
16953
(69248, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t112.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t212.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t312.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t412.txt
(223622, 33)
Hogar - Indiv merged:
(228327, 49)
No aglo agregado:
(456654, 50)
['2012-02-15T00:00:00.000000000' '2012-05-15T00:00:00.000000000'
 '2012-08-15T00:00:00.000000000' '2012-11-15T00:00:00.000000000']
deflactado:
(456654, 51)

P21        3444.209104
P47T       4896.191256
PP08D1     2718.381260
TOT_P12     184.187380
T_VI       1097.842130
V12_M       107.280365
V2_M        799.945412
V3_M         19.876116
V5_M         48.275938
dtype: float64

2013
17013
17379
17378
17486
(69224, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t113.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t213.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t313.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t413.txt
(222230, 33)
Hogar - Indiv merged:
(226546, 49)
No aglo agregado:
(453092, 50)
['2013-02-15T00:00:00.000000000' '2013-05-15T00:00:00.000000000'
 '2013-08-15T00:00:00.000000000' '2013-11-15T00:00:00.000000000']
deflactado:
(453092, 51)

P21        3579.164395
P47T       5119.247958
PP08D1     2815.809584
TOT_P12     182.129545
T_VI       1205.198207
V12_M       109.472672
V2_M        902.029054
V3_M         23.729075
V5_M         52.916564
dtype: float64

2014
17797
18780
19041
18909
(74481, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t114.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t214.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t314.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t414.txt
(241181, 33)
Hogar - Indiv merged:
(245363, 49)
No aglo agregado:
(490726, 50)
['2014-02-15T00:00:00.000000000' '2014-05-15T00:00:00.000000000'
 '2014-08-15T00:00:00.000000000' '2014-11-15T00:00:00.000000000']
deflactado:
(490726, 51)

P21        3328.735074
P47T       4808.536169
PP08D1     2645.097981
TOT_P12     176.013820
T_VI       1142.496839
V12_M        96.216928
V2_M        845.110885
V3_M         21.722489
V5_M         59.819329
dtype: float64

2015
18743
18875
(37601, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t115.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t215.txt
(120173, 33)
Hogar - Indiv merged:
(122102, 49)
No aglo agregado:
(244204, 50)
['2015-02-15T00:00:00.000000000' '2015-05-15T00:00:00.000000000']
deflactado:
(244204, 51)

P21        3416.307153
P47T       4980.678146
PP08D1     2725.163609
TOT_P12     192.175321
T_VI       1213.029017
V12_M       100.473956
V2_M        904.462589
V3_M         20.929256
V5_M         62.445144
dtype: float64

2016
18796
18800
18372
(55937, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t216.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t316.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t416.txt
(177341, 33)
Hogar - Indiv merged:
(179967, 49)
No aglo agregado:
(359934, 50)
['2016-05-15T00:00:00.000000000' '2016-08-15T00:00:00.000000000'
 '2016-11-15T00:00:00.000000000']
deflactado:
(359934, 51)

P21        2749.045342
P47T       4029.840687
PP08D1     5496.511113
TOT_P12     132.307129
T_VI       1135.864670
V12_M        79.130880
V2_M        887.429484
V3_M         26.210989
V5_M         63.172871
dtype: float64

2017
18477
18871
18806
18793
(74911, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t117.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t217.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t317.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t417.txt
(235100, 33)
Hogar - Indiv merged:
(239222, 49)
No aglo agregado:
(478444, 50)
['2017-02-15T00:00:00.000000000' '2017-05-15T00:00:00.000000000'
 '2017-08-15T00:00:00.000000000' '2017-11-15T00:00:00.000000000']
deflactado:
(478444, 51)

P21        2972.249739
P47T       4483.931035
PP08D1     5800.805773
TOT_P12     153.907375
T_VI       1305.407580
V12_M        86.450209
V2_M       1007.798589
V3_M         28.821726
V5_M         69.490611
dtype: float64

2018
18624
18586
18364
18616
(74151, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t118.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t218.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t318.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t418.txt
(229794, 33)
Hogar - Indiv merged:
(234346, 49)
No aglo agregado:
(468692, 50)
['2018-02-15T00:00:00.000000000' '2018-05-15T00:00:00.000000000'
 '2018-08-15T00:00:00.000000000' '2018-11-15T00:00:00.000000000']
deflactado:
(468692, 51)

P21        2883.379499
P47T       4413.771611
PP08D1     5514.424764
TOT_P12     165.728794
T_VI       1297.288147
V12_M        85.269311
V2_M        981.259236
V3_M         41.334907
V5_M         68.251372
dtype: float64

2019
19338
19251
18610
19035
(76165, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t119.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t219.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t319.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t419.txt
(234083, 33)
Hogar - Indiv merged:
(238760, 49)
No aglo agregado:
(477520, 50)
['2019-02-15T00:00:00.000000000' '2019-05-15T00:00:00.000000000'
 '2019-08-15T00:00:00.000000000' '2019-11-15T00:00:00.000000000']
deflactado:
(477520, 51)

P21        2597.867273
P47T       4044.710379
PP08D1     4912.533375
TOT_P12     160.096256
T_VI       1217.219903
V12_M        84.035915
V2_M        884.861267
V3_M         46.891636
V5_M         72.017423
dtype: float64

2020
16845
11976
13503
(42293, 19)
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t120.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t220.txt
./../../microdatos-EPH-INDEC/microdatos/individual/usu_individual_t320.txt
(130249, 33)
Hogar - Indiv merged:
(133386, 49)
No aglo agregado:
(266772, 50)
['2020-02-15T00:00:00.000000000' '2020-05-15T00:00:00.000000000'
 '2020-08-15T00:00:00.000000000']
deflactado:
(266772, 51)

P21        2228.213261
P47T       3908.797527
PP08D1     4692.954450
TOT_P12     145.622277
T_VI       1399.605311
V12_M        71.796973
V2_M        906.351154
V3_M         29.110079
V5_M        198.291522
dtype: float64

In [11]:
# ix
# EPH[col_mon]
# ix*EPH[col_mon].div(, 0)
# EPH[['Q'] + col_mon].merge(cpi, on = 'Q', how = 'left')['index'].values

In [12]:
# cpi

### Ranking de AGLOS y Regiones

In [13]:
# df_list = []
# for yr in [str(s) for s in [2006, 2011, 2016]]:
# # for yr in [str(s) for s in [2018, 2020]]:
# # for yr in [str(s) for s in [2020]]:  # Esto depende de los anios en que tengamos la microdata, podemos elegir
# # for yr in [str(s) for s in range(startyr, endyr)]:
#     print(yr)
#     train = pd.read_csv('./../data/training/EPHARG_train_'+yr[2:]+'.csv')
#     train = train.loc[train.P47T >= -0.001].fillna(0)#.sample(400000)
#     df_list += [train]
    
# train_df = pd.concat(df_list)

# AGLO_rk = train_df.loc[train_df.CAT_OCUP == 3].groupby(['AGLOMERADO'])[['P47T']].mean().sort_values('P47T').reset_index().reset_index().rename(columns = {'index':'AGLO_rk'})
# Reg_rk = train_df.loc[train_df.CAT_OCUP == 3].groupby(['Region'])[['P47T']].mean().sort_values('P47T').reset_index().reset_index().rename(columns = {'index':'Reg_rk'})

# AGLO_rk['AGLO_rk'] = AGLO_rk.AGLO_rk/AGLO_rk.AGLO_rk.max()
# AGLO_rk.to_csv('./../data/info/AGLO_rk', index = False)
# Reg_rk['Reg_rk'] = Reg_rk.Reg_rk/Reg_rk.Reg_rk.max()
# Reg_rk.to_csv('./../data/info/Reg_rk', index = False)

# # check it out
# # AGLO_rk.merge(pd.read_csv('./../data/info/aglo_labels.csv'))

## Guardar training dataset

In [14]:
AGLO_rk = pd.read_csv('./../data/info/AGLO_rk')
Reg_rk = pd.read_csv('./../data/info/Reg_rk')

df_list = []
for yr in [str(s) for s in range(startyr, endyr)]:
# for yr in [str(s) for s in range(startyr, endyr)]:
    print(yr)
    train = pd.read_csv('./../data/training/EPHARG_train_'+yr[2:]+'.csv')#.drop(['AGLO_rk', 'Reg_rk'], axis = 1)
    train = train.loc[train.P47T >= -0.001].fillna(0)
    train = train.merge(AGLO_rk[['AGLOMERADO', 'AGLO_rk']]).merge(Reg_rk[['Region', 'Reg_rk']])
    train.to_csv('./../data/training/EPHARG_train_'+yr[2:]+'.csv', index = False)

2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020

## Listo. Salvado el training set.

### Borradores sobre los nombres de columnas..

In [15]:
# # Misma info, distinto nombre. 
# # Censo INDEC 
# md_1 = table[['IX_TOT', 'P02', 'P03', 'CONDACT', 'AGLOMERADO', #las que no se erran, cant pers, sexo, edad, act, aglo
#     'V01', 'H05', 'H06', 'H07', 'H08', 'H09', 'H10', 'H11', 'H12', 'H16', 'H15', 'PROP', 'H14', 'H13',
#       'P07', 'P08', 'P09', 'P10', 'P05']] #las x que buscan matches un poquito mas laxamente


# #Mismas cosas, distinto nombre de columna para
# # EPH INDEC
# md_2 = EPH[['IX_TOT','CH04','CH06','CONDACT', 'AGLOMERADO',
#     'IV1', 'IV3', 'IV4','IV5','IV6','IV7','IV8','IV10','IV11','II1','II2','II7','II8','II9',
#     'CH09','CH10','CH12','CH13','CH15']]

# # # Controlar superposicion de columnas

# # for i in range(len(md_1.columns))[:2]: 
# #     print('\n')
# #     for md in [md_1, md_2]:
# #         col = md.columns[i]
# #         print(col)
# #         print(md[col].value_counts().sort_index()/len(md))

# md_2.columns = md_1.columns

In [16]:
# import numpy as np
# # Agregar $$$. En millones de usd
# # En millones de usd (USD = 30 ARS)
# _USD = 30.5 #ARS
# np.round(res_1.sum()/_USD/1e6, 1).sort_values().tail(14)

# #PPALES
# # negocio que no trabajo no laborable (V9_M)
# # alquiler no laborable (V8_M)
# # indemnizacion despido no laborable (V3_M)
# # comision Ocupacion ppal (PP08F1)
# # cuota alimentos no laborable (V12_M)
# # subsidio ayuda social no laborable (V5_M)
# # TOTAL otras ocupacions(TOT_P12)
# # jubilacion no laborable (V2_M)
# # TOTAL no laborables (T_VI)
# # sueldo Ocupacion ppal(PP08D1)
# # TOTAL Ocupacion ppal (P21)
# # TOTAL TOTAL (P47T)

In [17]:
# # Desoc, NA = 0. Not good.
# variables = ['PP07J', #turno habitual
#  'PP10D', #Desoc. Ha trabajado alguna vez?
#  'PP10C', #Desoc. Hizo changa mientras buscaba?
#  'PP07K', # Oc. ppal. Inc. serv. dom. Cobra con recibo
#  'PP07G2', # Oc. ppal. Inc. serv. dom. aguinaldo
#  'PP07G_59', # Oc. ppal. Inc. serv. dom. ninguno
#  'PP07G3', # Oc. ppal. Inc. serv. dom. dias enfermedad
#  'PP10E', # Desoc. Tiempo de que termino su ultimo trabajo/changa
#  'PP07H', # Oc. ppal. Inc. serv. dom. descuento jubilatorio
#  'PP07G4', # Oc. ppal. Inc. serv. dom. obra social
#  'PP07I', # Oc. ppal. Inc. serv. dom. Aporta jub por sí mismo 
#  'PP07G1', # Oc. ppal. Inc. serv. dom. vacaciones pagas
#  'CH07'] #Est civil

# #en miles de USD
# # res_byDPTO = res_DPTO.groupby(['DPTO', 'NOMDPTO', 'NOMPROV'])[variables].mean()
# res_byDPTO = res_DPTO.groupby(['RADIO_REF_ID'])[variables].mean()


# s = np.round(res_byDPTO, 2).sort_values(by = 'PP07K')#.head() 
# s.style.bar(color='#d65f5f')
# #  'CAT_OCUP', #CAT_INAC
# #  'CAT_INAC', #CAT_INAC

# #  'CH08', obra social/salud. nums altos como para mean
# # 'CH16', # Donde vivia hace 5. Desconfiable

In [18]:
# from IPython.core.display import display, HTML
# display(HTML("<style>.container { width:100% !important; }</style>"))

# for col in result.columns:
#     print('\n')
#     print(col)
#     df_ = result.loc[result.P03 > 2]
#     print(df_[col].value_counts().sort_index())